name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout submodules
        uses: actions/checkout@v2
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: Build (Pelican)
        shell: bash
        run: |
          sudo apt-get update
          cd src
          pip3 install -r requirements.txt
          make aws

      - name: Deploy (AWS S3)
        shell: bash
        env:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_access_key_secret: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          aws_s3_bucket: ${{ secrets.AWS_S3_BUCKET }}
          aws_default_region: ${{ secrets.AWS_DEFAULT_REGION }}
          aws_cloudfront_id: ${{ secrets.AWS_CLOUDFRONT_ID }}
        run: |
          sudo apt-get -y install awscli
          aws configure set aws_access_key_id ${aws_access_key_id}
          aws configure set aws_secret_access_key ${aws_access_key_secret}
          aws configure set default.region ${aws_default_region}
          aws s3 sync src/output/ s3://${aws_s3_bucket} --acl public-read --delete
          aws cloudfront create-invalidation --distribution-id ${aws_cloudfront_id} --paths "/*"
